ENT.Base 			= "npc_vj_bmsz_zecu"
ENT.Type 			= "ai"
ENT.PrintName 		= "Crabless Zombie Marine"
ENT.Author 			= "DrVrej"
ENT.Contact 		= "http://steamcommunity.com/groups/vrejgaming"
ENT.Purpose 		= "Spawn it and fight with it!"
ENT.Instructions 	= "Click on the spawnicon to spawn it."
ENT.Category		= "Black Mesa"